const PADDING_HORIZONTAL = 16
const PADDING_VERTICAL = 12
const MARGIN_BOTTOM_SMALL = 10
const MARGIN_BOTTOM_LARGE = 20

export { PADDING_HORIZONTAL, PADDING_VERTICAL, MARGIN_BOTTOM_SMALL, MARGIN_BOTTOM_LARGE }