const EMAIL_PLACEHOLDER = 'Your Email'
const PASSWORD_PLACEHOLDER = 'Password'
const CONFIRM_PASSWORD_PLACEHOLDER = 'Re-Enter Password'
const INVALID_EMAIL_ADDRESS = 'That email address is invalid!'

export {
    EMAIL_PLACEHOLDER,
    PASSWORD_PLACEHOLDER,
    CONFIRM_PASSWORD_PLACEHOLDER,
    INVALID_EMAIL_ADDRESS
}